[package]
name = "ringhopper-definitions"
authors = ["Snowy Mouse"]
version = "0.2.0"
description = "Engine and tag structure definitions for Ringhopper"
license = "GPL-3.0-only"
edition = "2021"

[dependencies]
serde_json = { version = "1.0", features = ["alloc"], default-features = false }
